name: Deploy and Sync

on:
  push:
    branches:
      - master

jobs:
  deploy_and_sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh 
          echo "${{secrets.SSH_PRIVATE_KEY}}" >~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 92.205.56.184 >> ~/.ssh/known_hosts
        shell: bash

      - name: Sync files with rsync
        run: |
          rsync --exclude=".git" -arv . maplecourt@92.205.56.184:arm-solutions/
        env:
          RSYNC_RSH: 'ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no'
        shell: bash
